erlang: correct patch-erts_configure.diff     Fixes https://trac.macports.org/ticket/19493
git-svn-id: https://svn.macports.org/repository/macports/trunk/dports@50480 d073be05-634f-4543-b044-5fe20cf6d1d6

diff --git a/lang/erlang/files/patch-erts_configure.diff b/lang/erlang/files/patch-erts_configure.diff
--- a/lang/erlang/files/patch-erts_configure.diff
+++ b/lang/erlang/files/patch-erts_configure.diff
@@ -1,14 +1,14 @@
 --- erts/configure.orig	2009-04-21 11:33:14.000000000 -0400
 +++ erts/configure	2009-04-21 10:49:56.000000000 -0400
-@@ -19528,6 +19742,91 @@
+@@ -19528,6 +19742,95 @@
    	esac
    fi
  fi
 +
 +case $ARCH-$OPSYS in
 +	amd64-darwin*|x86-darwin*)
-+		{ $as_echo "$as_me:$LINENO: checking For modern (leopard) style mcontext_t" >&5
-+$as_echo_n "checking For modern (leopard) style mcontext_t... " >&6; }
++		echo "$as_me:$LINENO: checking For modern (leopard) style mcontext_t" >&5
++echo $ECHO_N "checking For modern (leopard) style mcontext_t... $ECHO_C" >&6
 +		cat >conftest.$ac_ext <<_ACEOF
 +/* confdefs.h.  */
 +_ACEOF
@@ -46,43 +46,47 @@
 +}
 +_ACEOF
 +rm -f conftest.$ac_objext
-+if { (ac_try="$ac_compile"
-+case "(($ac_try" in
-+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-+  *) ac_try_echo=$ac_try;;
-+esac
-+eval ac_try_echo="\"\$as_me:$LINENO: $ac_try_echo\""
-+$as_echo "$ac_try_echo") >&5
-+  (eval "$ac_compile") 2>conftest.er1
++if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
++  (eval $ac_compile) 2>conftest.er1
 +  ac_status=$?
 +  grep -v '^ *+' conftest.er1 >conftest.err
 +  rm -f conftest.er1
 +  cat conftest.err >&5
-+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
-+  (exit $ac_status); } && {
-+	 test -z "$ac_c_werror_flag" ||
-+	 test ! -s conftest.err
-+       } && test -s conftest.$ac_objext; then
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); } &&
++	 { ac_try='test -z "$ac_c_werror_flag"
++			 || test ! -s conftest.err'
++  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
++  (eval $ac_try) 2>&5
++  ac_status=$?
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); }; } &&
++	 { ac_try='test -s conftest.$ac_objext'
++  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
++  (eval $ac_try) 2>&5
++  ac_status=$?
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); }; }; then
 +  darwin_mcontext_leopard=yes
 +else
-+  $as_echo "$as_me: failed program was:" >&5
++  echo "$as_me: failed program was:" >&5
 +sed 's/^/| /' conftest.$ac_ext >&5
 +
 +	darwin_mcontext_leopard=no
 +fi
 +
-+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
++rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
 +				if test X"$darwin_mcontext_leopard" = X"yes"; then
 +
 +cat >>confdefs.h <<\_ACEOF
 +#define DARWIN_MODERN_MCONTEXT /**/
 +_ACEOF
 +
-+				   { $as_echo "$as_me:$LINENO: result: yes" >&5
-+$as_echo "yes" >&6; }
++				   echo "$as_me:$LINENO: result: yes" >&5
++echo "${ECHO_T}yes" >&6
 +				else
-+				   { $as_echo "$as_me:$LINENO: result: no" >&5
-+$as_echo "no" >&6; }
++				   echo "$as_me:$LINENO: result: no" >&5
++echo "${ECHO_T}no" >&6
 +				fi
 +		;;
 +	*)
