fontforge:  * Updated to 20080927.  * Updated freetype bytecode interpreter to 2.3.7.  * dlopen() now uses only absolute paths to ensure libraries are taken from $prefix.  * Added libuninameslist dependency.  * Documentation is now installed into a versioned directory.  * Multilayered type3/svg fonts support is now always enabled.  * Aqua application is now correctly installed in /Application/MacPorts.
git-svn-id: https://svn.macports.org/repository/macports/trunk/dports@41786 d073be05-634f-4543-b044-5fe20cf6d1d6

diff --git a/graphics/fontforge/files/patch-configure.diff b/graphics/fontforge/files/patch-configure.diff
--- a/graphics/fontforge/files/patch-configure.diff
+++ b/graphics/fontforge/files/patch-configure.diff
@@ -1,51 +1,50 @@
---- configure.orig	2008-01-05 10:58:52.000000000 -0700
-+++ configure	2008-01-12 18:05:47.000000000 -0700
-@@ -2675,7 +2675,6 @@
+--- configure.orig	2008-11-10 09:16:23.000000000 +0100
++++ configure	2008-11-10 09:21:43.000000000 +0100
+@@ -2684,8 +2684,6 @@
  
  fi;
  
 -LDFLAGS="$LDFLAGS -L/usr/local/lib"
- 
+-
  case "$host" in
  *-apple-darwin*)
-@@ -2695,9 +2694,9 @@
+  gww_ismac="yes"
+@@ -2705,13 +2703,9 @@
   gww_define_caps_for_alt="1"
  
  
-- CPPFLAGS="$CPPFLAGS -I/sw/include"
-- LDFLAGS="$LDFLAGS -L/sw/lib"
-- gww_rpath="-rpath /sw/lib"
-+ CPPFLAGS="$CPPFLAGS -I@@PREFIX@@/include"
-+ LDFLAGS="$LDFLAGS -L@@PREFIX@@/lib"
-+ gww_rpath="-rpath @@PREFIX@@/lib"
+- if test -d /sw/include >/dev/null ; then
+-  CPPFLAGS="$CPPFLAGS -I/sw/include"
+- fi
+- if test -d /sw/lib >/dev/null ; then
+-  LDFLAGS="$LDFLAGS -L/sw/lib"
+-  gww_rpath="-rpath /sw/lib"
+- fi
++ CPPFLAGS="$CPPFLAGS -I@PREFIX@/include"
++ LDFLAGS="$LDFLAGS -L@PREFIX@/lib"
++ gww_rpath="-rpath @PREFIX@/lib"
+  LIBS="-Wl,/System/Library/Frameworks/Carbon.framework/Carbon $LIBS"
   LIBS="-Wl,/System/Library/Frameworks/CoreServices.framework/CoreServices $LIBS"
  
-  ;;
-@@ -19171,55 +19170,26 @@
+@@ -19738,55 +19732,8 @@
  
  fi
  
 -echo "$as_me:$LINENO: checking for /usr/include/libxml2/libxml" >&5
 -echo $ECHO_N "checking for /usr/include/libxml2/libxml... $ECHO_C" >&6
 -if test "${ac_cv_file__usr_include_libxml2_libxml+set}" = set; then
-+echo "$as_me:$LINENO: checking for @@PREFIX@@/include/libxml2/libxml" >&5
-+echo $ECHO_N "checking for @@PREFIX@@/include/libxml2/libxml... $ECHO_C" >&6
-+if test "${ac_cv_file__opt_local_include_libxml2_libxml+set}" = set; then
-   echo $ECHO_N "(cached) $ECHO_C" >&6
- else
-   test "$cross_compiling" = yes &&
-   { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
- echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
-    { (exit 1); exit 1; }; }
+-  echo $ECHO_N "(cached) $ECHO_C" >&6
+-else
+-  test "$cross_compiling" = yes &&
+-  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+-echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+-   { (exit 1); exit 1; }; }
 -if test -r "/usr/include/libxml2/libxml"; then
 -  ac_cv_file__usr_include_libxml2_libxml=yes
-+if test -r "@@PREFIX@@/include/libxml2/libxml"; then
-+  ac_cv_file__opt_local_include_libxml2_libxml=yes
- else
+-else
 -  ac_cv_file__usr_include_libxml2_libxml=no
-+  ac_cv_file__opt_local_include_libxml2_libxml=no
- fi
- fi
+-fi
+-fi
 -echo "$as_me:$LINENO: result: $ac_cv_file__usr_include_libxml2_libxml" >&5
 -echo "${ECHO_T}$ac_cv_file__usr_include_libxml2_libxml" >&6
 -if test $ac_cv_file__usr_include_libxml2_libxml = yes; then
@@ -66,11 +65,7 @@
 -else
 -  ac_cv_file__usr_local_include_libxml2_libxml=no
 -fi
-+echo "$as_me:$LINENO: result: $ac_cv_file__opt_local_include_libxml2_libxml" >&5
-+echo "${ECHO_T}$ac_cv_file__opt_local_include_libxml2_libxml" >&6
-+if test $ac_cv_file__opt_local_include_libxml2_libxml = yes; then
-+  CFLAGS="$CFLAGS -I@@PREFIX@@/include -I@@PREFIX@@/include/libxml2/"
- fi
+-fi
 -echo "$as_me:$LINENO: result: $ac_cv_file__usr_local_include_libxml2_libxml" >&5
 -echo "${ECHO_T}$ac_cv_file__usr_local_include_libxml2_libxml" >&6
 -if test $ac_cv_file__usr_local_include_libxml2_libxml = yes; then
@@ -83,7 +78,8 @@
 -fi
 -
 -fi
--
+ 
++CFLAGS="$CFLAGS -I@PREFIX@/include -I@PREFIX@/include/libxml2"
  
  
  echo "$as_me:$LINENO: checking for DGifOpenFileName in -lgif" >&5
