Update leiningen to 1.0.1, fixes https://trac.macports.org/ticket/23012
git-svn-id: https://svn.macports.org/repository/macports/trunk/dports@64045 d073be05-634f-4543-b044-5fe20cf6d1d6

diff --git a/devel/leiningen/files/patch-bin-lein.diff b/devel/leiningen/files/patch-bin-lein.diff
--- a/devel/leiningen/files/patch-bin-lein.diff
+++ b/devel/leiningen/files/patch-bin-lein.diff
@@ -1,46 +1,65 @@
-diff --git a/bin/lein b/bin/lein
-index 92546b1..a90c43f 100755
---- a/bin/lein
-+++ b/bin/lein
-@@ -2,23 +2,13 @@
+--- a/bin/lein	2009-12-23 21:04:30.000000000 -0800
++++ b/bin/lein	2009-12-23 21:12:07.000000000 -0800
+@@ -2,9 +2,9 @@
  
- # TODO: this gives us a trailing colon
- VERSION=0.5.0
--LIBS="$(find -H lib/ -mindepth 2> /dev/null 1 -maxdepth 1 -print0 | tr \\0 \:)"
+ VERSION="1.0.1"
+ 
+-CLASSPATH="$(find -H lib/ -mindepth 2> /dev/null 1 -maxdepth 1 -print0 | tr \\0 \:)"
+-LEIN_JAR="$HOME/.m2/repository/leiningen/leiningen/$VERSION/leiningen-$VERSION-standalone.jar"
+-CLOJURE_JAR="$HOME/.m2/repository/org/clojure/clojure/1.1.0-master-SNAPSHOT/clojure-1.1.0-master-SNAPSHOT.jar"
 +PREFIX=__PREFIX__
-+LIBS="$(find -H $PREFIX -name \*.jar -print0 | tr \\0 \:)"
- CLASSPATH="src/:classes/:$LIBS"
--LEIN_JAR=$HOME/.m2/repository/leiningen/leiningen/$VERSION/leiningen-$VERSION.jar
++CLASSPATH="$(find -H $PREFIX -name \*.jar 2> /dev/null -print0 | tr \\0 \:)"
++CLOJURE_JAR="$PREFIX/local/share/java/clojure/lib/clojure.jar"
  
- # this needs to exist before the JVM is launched apparently
- mkdir -p classes
+ # normalize $0 on certain BSDs
+ if [ "$(dirname $0)" = "." ]; then
+@@ -26,28 +26,6 @@
  
--# If we are not running from a checkout
--if [ ! -r "bin/lein" ]; then
+ BIN_DIR="$(dirname "$SCRIPT")"
+ 
+-if [ -r "$BIN_DIR/../src/leiningen/core.clj" ]; then
+-    # Running from source checkout
+-    LEIN_DIR="$(dirname "$BIN_DIR")"
+-    LEIN_LIBS="$(find -H $LEIN_DIR/lib -mindepth 2> /dev/null 1 -maxdepth 1 -print0 | tr \\0 \:)"
+-    CLASSPATH="$LEIN_DIR/src:$LEIN_LIBS:$CLASSPATH"
+-
+-    if [ "$LEIN_LIBS" = "" -a "$1" != "self-install" ]; then
+-        echo "Your Leiningen development checkout is missing its dependencies."
+-        echo "Please download a stable version of Leiningen to fetch the deps."
+-        echo "See the \"Hacking\" section of the readme for details."
+-        exit 1
+-    fi
+-else
+-    # Not running from a checkout
+-    CLASSPATH="$LEIN_JAR:$CLASSPATH"
+-
 -    if [ ! -r "$LEIN_JAR" -a "$1" != "self-install" ]; then
 -        echo "Leiningen is not installed. Please run \"lein self-install\"."
 -        exit 1
 -    fi
--
--    CLASSPATH="$CLASSPATH:$LEIN_JAR"
 -fi
 -
- if [ "$1" = "test" ]; then
-     CLASSPATH=test/:$CLASSPATH
+ if [ $DEBUG ]; then
+     echo $CLASSPATH
  fi
-@@ -37,15 +27,6 @@ fi
+@@ -60,20 +38,6 @@
+ 
  if [ "$1" = "repl" ]; then
-     # If repl used leiningen.core then there'd be no way to bootstrap AOT
-     java -cp "$CLASSPATH" clojure.main
+     java -client $JAVA_OPTS -cp "src/:classes/:$CLASSPATH" jline.ConsoleRunner clojure.main ${@:2}
 -elif [ "$1" = "self-install" ]; then
+-    if [[ $VERSION == *SNAPSHOT ]]; then
+-        echo "The self-install task is only meant for stable releases."
+-        echo "See the \"Hacking\" section of the README."
+-        exit 1
+-    fi
 -    echo "Downloading Leiningen now..."
 -    mkdir -p `dirname "$LEIN_JAR"`
--    LEIN_URL=http://repo.technomancy.us/leiningen-$VERSION.jar
+-    LEIN_URL="http://repo.technomancy.us/leiningen-$VERSION-standalone.jar"
 -    if type -p curl >/dev/null 2>&1; then
 -        exec curl -o "$LEIN_JAR" "$LEIN_URL"
 -    else
 -        exec wget -O "$LEIN_JAR" "$LEIN_URL"
 -    fi
  else
-     if [ -z "$1" ]; then
-         echo "$0 missing task"
+     exec java -Xbootclasspath/a:"$CLOJURE_JAR" -client $JAVA_OPTS -cp "$CLASSPATH" -Dleiningen.version="$VERSION" clojure.main -e "(use 'leiningen.core)(-main $ESCAPED_ARGS)"
+ fi
