Update to leiningen 1.1.0
git-svn-id: https://svn.macports.org/repository/macports/trunk/dports@64047 d073be05-634f-4543-b044-5fe20cf6d1d6

diff --git a/devel/leiningen/files/patch-bin-lein.diff b/devel/leiningen/files/patch-bin-lein.diff
--- a/devel/leiningen/files/patch-bin-lein.diff
+++ b/devel/leiningen/files/patch-bin-lein.diff
@@ -1,22 +1,33 @@
---- a/bin/lein	2009-12-23 21:04:30.000000000 -0800
-+++ b/bin/lein	2009-12-23 21:12:07.000000000 -0800
-@@ -2,9 +2,9 @@
+--- a/bin/lein.orig	2010-02-20 15:51:26.000000000 -0500
++++ b/bin/lein	2010-02-20 15:55:13.000000000 -0500
+@@ -2,51 +2,9 @@
  
- VERSION="1.0.1"
+ VERSION="1.1.0"
  
--CLASSPATH="$(find -H lib/ -mindepth 2> /dev/null 1 -maxdepth 1 -print0 | tr \\0 \:)"
+-CLASSPATH="$(find lib/ -follow -mindepth 1 -maxdepth 1 -print0 2> /dev/null | tr \\0 \:)"
 -LEIN_JAR="$HOME/.m2/repository/leiningen/leiningen/$VERSION/leiningen-$VERSION-standalone.jar"
--CLOJURE_JAR="$HOME/.m2/repository/org/clojure/clojure/1.1.0-master-SNAPSHOT/clojure-1.1.0-master-SNAPSHOT.jar"
-+PREFIX=__PREFIX__
-+CLASSPATH="$(find -H $PREFIX -name \*.jar 2> /dev/null -print0 | tr \\0 \:)"
-+CLOJURE_JAR="$PREFIX/local/share/java/clojure/lib/clojure.jar"
- 
- # normalize $0 on certain BSDs
- if [ "$(dirname $0)" = "." ]; then
-@@ -26,28 +26,6 @@
- 
- BIN_DIR="$(dirname "$SCRIPT")"
- 
+-CLOJURE_JAR="$HOME/.m2/repository/org/clojure/clojure/1.1.0/clojure-1.1.0.jar"
+-
+-# normalize $0 on certain BSDs
+-if [ "$(dirname $0)" = "." ]; then
+-    SCRIPT="$(which $(basename $0))"
+-else
+-    SCRIPT="$0"
+-fi
+-
+-# resolve symlinks to the script itself portably
+-while [ -h "$SCRIPT" ] ; do
+-    ls=`ls -ld "$SCRIPT"`
+-    link=`expr "$ls" : '.*-> \(.*\)$'`
+-    if expr "$link" : '/.*' > /dev/null; then
+-        SCRIPT="$link"
+-    else
+-        SCRIPT="`dirname "$SCRIPT"`/$link"
+-    fi
+-done
+-
+-BIN_DIR="$(dirname "$SCRIPT")"
+-
 -if [ -r "$BIN_DIR/../src/leiningen/core.clj" ]; then
 -    # Running from source checkout
 -    LEIN_DIR="$(dirname "$BIN_DIR")"
@@ -38,14 +49,28 @@
 -        exit 1
 -    fi
 -fi
--
++PREFIX=__PREFIX__
++CLASSPATH="$(find -H $PREFIX -name \*.jar 2> /dev/null -print0 | tr \\0 \:)"
++CLOJURE_JAR="$PREFIX/local/share/java/clojure/lib/clojure.jar"
+ 
  if [ $DEBUG ]; then
      echo $CLASSPATH
- fi
-@@ -60,20 +38,6 @@
+@@ -58,11 +16,6 @@
+   ESCAPED_ARGS="$ESCAPED_ARGS"' "'$(echo $ARG | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')'"'
+ done
  
+-HTTP_CLIENT="wget -O"
+-if type -p curl >/dev/null 2>&1; then
+-    HTTP_CLIENT="curl -L -o"
+-fi
+-
  if [ "$1" = "repl" ]; then
-     java -client $JAVA_OPTS -cp "src/:classes/:$CLASSPATH" jline.ConsoleRunner clojure.main ${@:2}
+     if [ -r project.clj ]; then
+         echo "Warning: the repl task currently doesn't honor some project.clj"
+@@ -72,43 +25,6 @@
+         echo
+     fi
+     $RLWRAP java -client $JAVA_OPTS -cp "src/:classes/:$CLASSPATH" jline.ConsoleRunner clojure.main ${@:2}
 -elif [ "$1" = "self-install" ]; then
 -    if [[ $VERSION == *SNAPSHOT ]]; then
 -        echo "The self-install task is only meant for stable releases."
@@ -54,11 +79,34 @@
 -    fi
 -    echo "Downloading Leiningen now..."
 -    mkdir -p `dirname "$LEIN_JAR"`
--    LEIN_URL="http://repo.technomancy.us/leiningen-$VERSION-standalone.jar"
--    if type -p curl >/dev/null 2>&1; then
--        exec curl -o "$LEIN_JAR" "$LEIN_URL"
+-    LEIN_URL="http://github.com/downloads/technomancy/leiningen/leiningen-$VERSION-standalone.jar"
+-    exec $HTTP_CLIENT "$LEIN_JAR" "$LEIN_URL"
+-elif [ "$1" = "upgrade" ]; then
+-    if [[ $VERSION == *SNAPSHOT ]]; then
+-        echo "The upgrade task is only meant for stable releases."
+-        echo "See the \"Hacking\" section of the README."
+-        exit 1
+-    fi
+-    if [ ! -w "$SCRIPT" ]; then
+-        echo "You do not have permission to upgrade the installation in $SCRIPT"
+-        exit 1
 -    else
--        exec wget -O "$LEIN_JAR" "$LEIN_URL"
+-        echo "The script at $SCRIPT will be upgraded to the latest stable version."
+-        echo -n "Do you want to continue [Y/n]? "
+-        read RESP
+-        case "$RESP" in
+-            y|Y|"")
+-                echo
+-                echo "Upgrading..."
+-                LEIN_SCRIPT_URL="http://github.com/technomancy/leiningen/raw/stable/bin/lein"
+-                $HTTP_CLIENT "$SCRIPT" "$LEIN_SCRIPT_URL" \
+-                    && chmod +x "$SCRIPT" \
+-                    && echo && $SCRIPT self-install && echo && echo "Now running" `$SCRIPT version`
+-                exit $?;;
+-            *)
+-                echo "Aborted."
+-                exit 1;;
+-        esac
 -    fi
  else
      exec java -Xbootclasspath/a:"$CLOJURE_JAR" -client $JAVA_OPTS -cp "$CLASSPATH" -Dleiningen.version="$VERSION" clojure.main -e "(use 'leiningen.core)(-main $ESCAPED_ARGS)"
