libdlna: add patches to fix build against latest ffmpeg 0.5, increment revision. Closes https://trac.macports.org/ticket/18856 (maintainer timeout).
git-svn-id: https://svn.macports.org/repository/macports/trunk/dports@48291 d073be05-634f-4543-b044-5fe20cf6d1d6

diff --git a/devel/libdlna/files/patch-configure.diff b/devel/libdlna/files/patch-configure.diff
--- a/devel/libdlna/files/patch-configure.diff
+++ b/devel/libdlna/files/patch-configure.diff
@@ -1,6 +1,18 @@
---- configure	2007-12-09 08:03:36.000000000 -0500
-+++ configure.new	2008-01-12 14:41:04.000000000 -0500
-@@ -720,7 +720,7 @@
+--- configure.orig	2007-11-26 12:47:43.000000000 -0800
++++ configure	2009-03-15 14:18:03.000000000 -0700
+@@ -610,9 +610,9 @@
+ fi
+ 
+ echolog "Checking for libavformat ..."
+-check_lib ffmpeg/avformat.h av_register_all -lavformat || die "Error, can't find libavformat !"
++check_lib libavformat/avformat.h av_register_all -lavformat || die "Error, can't find libavformat !"
+ echolog "Checking for libavcodec ..."
+-check_lib ffmpeg/avcodec.h avcodec_register_all -lavcodec || die "Error, can't find libavcodec !"
++check_lib libavcodec/avcodec.h avcodec_register_all -lavcodec || die "Error, can't find libavcodec !"
+ 
+ #################################################
+ #   version
+@@ -688,7 +688,7 @@
  fi
  append_config "EXTRALIBS=$extralibs"
  
