texlive: update to 2012 release [merge from /users/dports/ports to trunk]
git-svn-id: https://svn.macports.org/repository/macports/trunk/dports@95340 d073be05-634f-4543-b044-5fe20cf6d1d6

diff --git a/tex/texlive-bin/files/patch-texk_texlive_linked_scripts_Makefile.in.diff b/tex/texlive-bin/files/patch-texk_texlive_linked_scripts_Makefile.in.diff
--- a/tex/texlive-bin/files/patch-texk_texlive_linked_scripts_Makefile.in.diff
+++ b/tex/texlive-bin/files/patch-texk_texlive_linked_scripts_Makefile.in.diff
@@ -1,59 +1,67 @@
---- texk/texlive/linked_scripts/Makefile.in.orig	2011-06-20 17:00:53.000000000 -0400
-+++ texk/texlive/linked_scripts/Makefile.in	2011-06-20 20:31:41.000000000 -0400
-@@ -291,6 +291,7 @@
+--- texk/texlive/linked_scripts/Makefile.in.orig	2012-06-14 18:15:41.000000000 -0400
++++ texk/texlive/linked_scripts/Makefile.in	2012-06-14 18:18:22.000000000 -0400
+@@ -215,7 +215,7 @@
+ # dangling symlinks produced by `make install'.
+ # The instances in texmf* are the masters (except when it is CTAN).
  #
- # We support both multiplatform and non-multiplatform builds.
- #
-+# MacPorts: hard-code link destinations instead of using relative ones
- runscript = $(top_srcdir)/w32_wrapper/runscript.exe
- @WIN32_TRUE@WINEXT = $(EXEEXT)
- all: all-am
-@@ -619,12 +620,7 @@
+-texmf_scriptsdir = $(datarootdir)/texmf/scripts
++texmf_scriptsdir = @@TEXMFMAIN@@/scripts
+ texmf_shell_scripts = \
+ 	simpdftex/simpdftex
+ 
+@@ -231,7 +231,7 @@
+ 	$(texmf_shell_scripts) \
+ 	$(texmf_other_scripts)
+ 
+-texmf_dist_scriptsdir = $(datarootdir)/texmf-dist/scripts
++texmf_dist_scriptsdir = @@TEXMFDIST@@/scripts
+ texmf_dist_shell_scripts = \
+ 	bibexport/bibexport.sh \
+ 	installfont/installfont-tl \
+@@ -672,25 +672,20 @@
  @WIN32_TRUE@	  echo "$(INSTALL_SCRIPT) '$(runscript)' '$(DESTDIR)$(bindir)/$$link.exe'"; \
  @WIN32_TRUE@	  $(INSTALL_SCRIPT) $(runscript) $(DESTDIR)$(bindir)/$$link.exe || exit 1; \
  @WIN32_TRUE@	done
--@WIN32_FALSE@	case "$(bindir)" in \
--@WIN32_FALSE@	  */bin) $(MAKE) $(AM_MAKEFLAGS) REL=.. install-links;; \
--@WIN32_FALSE@	  */bin/*) $(MAKE) $(AM_MAKEFLAGS) REL=../.. install-links;; \
--@WIN32_FALSE@	  *) echo "strange directory '$(bindir)' for linked scripts" >&2; \
--@WIN32_FALSE@	     exit 1;; \
--@WIN32_FALSE@	esac
-+@WIN32_FALSE@	$(MAKE) $(AM_MAKEFLAGS) install-links
- 
+-@WIN32_FALSE@	@REL=`$(relpath) '$(DESTDIR)' '$(bindir)' '$(datarootdir)'`; \
+-@WIN32_FALSE@	if test -z "$$REL"; then \
+-@WIN32_FALSE@	  echo 'unable to compute relative path for linked scripts' >&2; \
+-@WIN32_FALSE@	  exit 1; \
+-@WIN32_FALSE@	fi; \
+ @WIN32_FALSE@	cd $(DESTDIR)$(bindir) && \
+ @WIN32_FALSE@	  for s in $(nobase_dist_texmf_scripts_SCRIPTS); do \
+ @WIN32_FALSE@	    target=`basename $$s | sed 's,\.[^/]*$$,,' | tr '[A-Z]' '[a-z]'`; \
+ @WIN32_FALSE@	    rm -f $$target; \
+-@WIN32_FALSE@	    echo "creating link '$$target' -> '$$REL/texmf/scripts/$$s'"; \
+-@WIN32_FALSE@	    $(LN_S) $$REL/texmf/scripts/$$s $$target || exit 1; \
++@WIN32_FALSE@	    echo "creating link '$$target' -> '@@TEXMFMAIN@@/scripts/$$s'"; \
++@WIN32_FALSE@	    $(LN_S) @@TEXMFMAIN@@/scripts/$$s $$target || exit 1; \
+ @WIN32_FALSE@	  done && \
+ @WIN32_FALSE@	  for s in $(nobase_dist_texmf_dist_scripts_SCRIPTS); do \
+ @WIN32_FALSE@	    target=`basename $$s | tr '[A-Z]' '[a-z]'`; \
+ @WIN32_FALSE@	    echo "$$s" | grep listings-ext.sh >/dev/null \
+ @WIN32_FALSE@	    || target=`echo $$target | sed 's,\.[^/]*$$,,'`; \
+ @WIN32_FALSE@	    rm -f $$target; \
+-@WIN32_FALSE@	    echo "creating link '$$target' -> '$$REL/texmf-dist/scripts/$$s'"; \
+-@WIN32_FALSE@	    $(LN_S) $$REL/texmf-dist/scripts/$$s $$target || exit 1; \
++@WIN32_FALSE@	    echo "creating link '$$target' -> '@@TEXMFDIST@@/scripts/$$s'"; \
++@WIN32_FALSE@	    $(LN_S) @@TEXMFDIST@@/scripts/$$s $$target || exit 1; \
+ @WIN32_FALSE@	  done && \
+ @WIN32_FALSE@	  for s in $(bin_links); do \
+ @WIN32_FALSE@	    link=`echo $$s | sed 's,.*:,,'`; \
+@@ -698,15 +693,7 @@
+ @WIN32_FALSE@	    rm -f $$link; \
+ @WIN32_FALSE@	    echo "creating link '$$link' -> '$$file'"; \
+ @WIN32_FALSE@	    $(LN_S) $$file $$link || exit 1; \
+-@WIN32_FALSE@	  done && \
+-@WIN32_FALSE@	  if test -d "$$REL/texmf/doc/man" \
+-@WIN32_FALSE@	     && test -z "$(TL_INSTALL_OMIT_MAN_LINK)" \
+-@WIN32_FALSE@	     && (test -h man || test ! -e man); then \
+-@WIN32_FALSE@	    echo "creating link 'man' -> '$$REL/texmf/doc/man'"; \
+-@WIN32_FALSE@	    rm -f man; \
+-@WIN32_FALSE@	    (ln -s "$$REL/texmf/doc/man" man || :); \
+-@WIN32_FALSE@	  else :; fi
+-
++@WIN32_FALSE@	  done
  .PHONY: install-links
  install-links:
-@@ -632,16 +628,16 @@
- 	  for s in $(nobase_dist_texmf_scripts_SCRIPTS); do \
- 	    target=`basename $$s | sed 's,\.[^/]*$$,,' | tr '[A-Z]' '[a-z]'`; \
- 	    rm -f $$target; \
--	    echo "creating link '$$target' -> '$(REL)/texmf/scripts/$$s'"; \
--	    $(LN_S) $(REL)/texmf/scripts/$$s $$target || exit 1; \
-+	    echo "creating link '$$target' -> '@@TEXMFMAIN@@/scripts/$$s'"; \
-+	    $(LN_S) @@TEXMFMAIN@@/scripts/$$s $$target || exit 1; \
- 	  done && \
- 	  for s in $(nobase_dist_texmf_dist_scripts_SCRIPTS); do \
- 	    target=`basename $$s | tr '[A-Z]' '[a-z]'`; \
- 	    echo "$$s" | grep listings-ext.sh >/dev/null \
- 	    || target=`echo $$target | sed 's,\.[^/]*$$,,'`; \
- 	    rm -f $$target; \
--	    echo "creating link '$$target' -> '$(REL)/texmf-dist/scripts/$$s'"; \
--	    $(LN_S) $(REL)/texmf-dist/scripts/$$s $$target || exit 1; \
-+	    echo "creating link '$$target' -> '@@TEXMFDIST@@/scripts/$$s'"; \
-+	    $(LN_S) @@TEXMFDIST@@/scripts/$$s $$target || exit 1; \
- 	  done && \
- 	  for s in $(bin_links); do \
- 	    link=`echo $$s | sed 's,.*:,,'`; \
-@@ -649,12 +645,7 @@
- 	    rm -f $$link; \
- 	    echo "creating link '$$link' -> '$$file'"; \
- 	    $(LN_S) $$file $$link || exit 1; \
--	  done && \
--	  rm -f man && \
--	  if test -d $(REL)/texmf/doc/man; then \
--	    echo "creating link 'man' -> '$(REL)/texmf/doc/man'" && \
--	    (ln -s $(REL)/texmf/doc/man man || :); \
--	  else :; fi
-+	  done
  
- uninstall-hook:
- 	@for s in $(nobase_dist_texmf_scripts_SCRIPTS) $(nobase_dist_texmf_dist_scripts_SCRIPTS); do \
diff --git a/tex/texlive-bin/files/patch-utils_chktex_Makefile.in.diff b/tex/texlive-bin/files/patch-utils_chktex_Makefile.in.diff
--- a/tex/texlive-bin/files/patch-utils_chktex_Makefile.in.diff
+++ b/tex/texlive-bin/files/patch-utils_chktex_Makefile.in.diff
@@ -1,6 +1,6 @@
---- utils/chktex/Makefile.in.orig	2011-07-13 21:28:48.000000000 -0400
-+++ utils/chktex/Makefile.in	2011-07-13 21:32:23.000000000 -0400
-@@ -249,12 +249,12 @@
+--- utils/chktex/Makefile.in.orig	2012-06-14 18:19:36.000000000 -0400
++++ utils/chktex/Makefile.in	2012-06-14 18:20:52.000000000 -0400
+@@ -287,12 +287,12 @@
  	$(CHKTEX_TREE)/deweb.1
  
  perl_scripts = deweb
@@ -10,29 +10,26 @@
  all_scripts = $(lua_scripts) $(perl_scripts) $(shell_scripts)
  @WIN32_TRUE@@WIN32_WRAP_TRUE@wrappers = $(all_scripts:=.exe)
  @WIN32_TRUE@@WIN32_WRAP_TRUE@runscript = $(top_srcdir)/../../texk/texlive/w32_wrapper/runscript.exe
--texmfdir = ${prefix}/$(scriptsdir)
+-texmfdir = $(datarootdir)/$(scriptsdir)
 +texmfdir = @@TEXMFMAIN@@/$(scriptsdir)
  nodist_texmf_SCRIPTS = $(perl_scripts:=.pl)
  @WIN32_FALSE@bin_SCRIPTS = $(CHKTEX_TREE)/chkweb
  
-@@ -1121,19 +1121,14 @@
+@@ -1205,16 +1205,11 @@
  
- # We support both multiplatform and non-multiplatform builds.
+ # We support native builds, multiplatform or not, as well as distro builds.
  install-links:
--	case "$(bindir)" in \
--	  */bin) $(MAKE) $(AM_MAKEFLAGS) REL=.. TYPE=$(TYPE) EXT=$(EXT) make-links;; \
--	  */bin/*) $(MAKE) $(AM_MAKEFLAGS) REL=../.. TYPE=$(TYPE) EXT=$(EXT) make-links;; \
--	  *) echo "strange directory '$(bindir)' for linked $(TYPE) scripts" >&2; \
--	     exit 1;; \
--	esac
-+	$(MAKE) $(AM_MAKEFLAGS) TYPE=$(TYPE) EXT=$(EXT) make-links
- 
- make-links:
- 	@cd $(DESTDIR)$(bindir) && \
+-	@REL=`$(SHELL) $(srcdir)/../../build-aux/relpath '$(DESTDIR)' '$(bindir)' '$(datarootdir)'`; \
+-	if test -z "$$REL"; then \
+-	  echo 'unable to compute relative path for linked $(TYPE) scripts' >&2; \
+-	  exit 1; \
+-	fi; \
+ 	cd $(DESTDIR)$(bindir) && \
  	  for f in $($(TYPE)_scripts); do \
  	    rm -f $$f; \
- 	    echo "creating link '$$f' -> '$(REL)/$(scriptsdir)/$$f.$(EXT)'"; \
--	    $(LN_S) $(REL)/$(scriptsdir)/$$f.$(EXT) $$f || exit 1; \
+-	    echo "creating link '$$f' -> '$$REL/$(scriptsdir)/$$f.$(EXT)'"; \
+-	    $(LN_S) $$REL/$(scriptsdir)/$$f.$(EXT) $$f || exit 1; \
++	    echo "creating link '$$f' -> '$(texmfdir)/$$f.$(EXT)'"; \
 +	    $(LN_S) $(texmfdir)/$$f.$(EXT) $$f || exit 1; \
  	  done  
  
