grass7: change a patch file to make install target comply with DESTDIR

diff --git a/gis/grass7/files/patch-Install_make.diff b/gis/grass7/files/patch-Install_make.diff
--- a/gis/grass7/files/patch-Install_make.diff
+++ b/gis/grass7/files/patch-Install_make.diff
@@ -1,5 +1,5 @@
---- include/Make/Install.make.orig	2020-04-27 11:15:39.000000000 +0200
-+++ include/Make/Install.make	2020-04-27 10:57:13.000000000 +0200
+--- Install.make.orig	2020-05-10 13:10:50.000000000 +0200
++++ Install.make	2020-05-10 13:12:43.000000000 +0200
 @@ -54,7 +54,7 @@
  	while [ ! -d "$$INST_PATH" ]; do \
  		INST_PATH=`dirname $$INST_PATH`; \
@@ -9,6 +9,15 @@
  		echo "ERROR: Directory $$INST_PATH is a parent directory of your" >&2 ; \
  		echo "  install directory $(INST_DIR) and is not writable." >&2 ; \
  		echo "  Perhaps you need root access." >&2 ; \
+@@ -63,7 +63,7 @@
+ 	fi
+ 
+ install-check-writable:
+-	@ if [ -d "$(INST_DIR)" -a ! -w "$(INST_DIR)" ] ; then \
++	@ if [ -d "$(DESTDIR)$(INST_DIR)" -a ! -w "$(DESTDIR)$(INST_DIR)" ] ; then \
+ 		echo "ERROR: Your install directory $(INST_DIR) is not writable." >&2 ; \
+ 		echo "  Perhaps you need root access." >&2 ; \
+ 		echo "  Installation aborted, exiting Make." >&2 ; \
 @@ -71,7 +71,7 @@
  	fi
  
