grass7: fix upgrading failure
Fixes: https://trac.macports.org/ticket/60445

diff --git a/gis/grass7/files/patch-Install_make.diff b/gis/grass7/files/patch-Install_make.diff
--- a/gis/grass7/files/patch-Install_make.diff
+++ b/gis/grass7/files/patch-Install_make.diff
@@ -9,6 +9,15 @@
  		echo "ERROR: Directory $$INST_PATH is a parent directory of your" >&2 ; \
  		echo "  install directory $(INST_DIR) and is not writable." >&2 ; \
  		echo "  Perhaps you need root access." >&2 ; \
+@@ -63,7 +63,7 @@
+ 	fi
+ 
+ install-check-writable:
+-	@ if [ -d "$(INST_DIR)" -a ! -w "$(INST_DIR)" ] ; then \
++	@ if [ -d "$(DESTDIR)$(INST_DIR)" -a ! -w "$(DESTDIR)$(INST_DIR)" ] ; then \
+ 		echo "ERROR: Your install directory $(INST_DIR) is not writable." >&2 ; \
+ 		echo "  Perhaps you need root access." >&2 ; \
+ 		echo "  Installation aborted, exiting Make." >&2 ; \
 @@ -71,7 +71,7 @@
  	fi
  
