pcre: update to 8.30
git-svn-id: https://svn.macports.org/repository/macports/trunk/dports@92835 d073be05-634f-4543-b044-5fe20cf6d1d6

diff --git a/devel/pcre/files/configure.patch b/devel/pcre/files/configure.patch
--- a/devel/pcre/files/configure.patch
+++ b/devel/pcre/files/configure.patch
@@ -1,13 +1,13 @@
---- configure.orig	2011-01-15 22:27:58.000000000 +1100
-+++ configure	2011-09-21 18:33:45.000000000 +1000
-@@ -15635,37 +15635,13 @@
+--- configure.orig	2012-02-04 06:55:43.000000000 -0600
++++ configure	2012-05-08 17:05:19.000000000 -0500
+@@ -16647,37 +16647,13 @@
  
  # Check for the availabiity of libreadline
  
 -for ac_header in readline/readline.h
 -do :
 -  ac_fn_c_check_header_mongrel "$LINENO" "readline/readline.h" "ac_cv_header_readline_readline_h" "$ac_includes_default"
--if test "x$ac_cv_header_readline_readline_h" = x""yes; then :
+-if test "x$ac_cv_header_readline_readline_h" = xyes; then :
 -  cat >>confdefs.h <<_ACEOF
 -#define HAVE_READLINE_READLINE_H 1
 -_ACEOF
@@ -19,7 +19,7 @@
 -for ac_header in readline/history.h
 -do :
 -  ac_fn_c_check_header_mongrel "$LINENO" "readline/history.h" "ac_cv_header_readline_history_h" "$ac_includes_default"
--if test "x$ac_cv_header_readline_history_h" = x""yes; then :
+-if test "x$ac_cv_header_readline_history_h" = xyes; then :
 -  cat >>confdefs.h <<_ACEOF
 -#define HAVE_READLINE_HISTORY_H 1
 -_ACEOF
@@ -32,7 +32,7 @@
 -$as_echo_n "checking for readline in -lreadline... " >&6; }
 +{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for readline in -ledit" >&5
 +$as_echo_n "checking for readline in -ledit... " >&6; }
- if test "${ac_cv_lib_readline_readline+set}" = set; then :
+ if ${ac_cv_lib_readline_readline+:} false; then :
    $as_echo_n "(cached) " >&6
  else
    ac_check_lib_save_LIBS=$LIBS
@@ -41,7 +41,7 @@
  cat confdefs.h - <<_ACEOF >conftest.$ac_ext
  /* end confdefs.h.  */
  
-@@ -15868,15 +15844,7 @@
+@@ -17140,14 +17116,6 @@
  # Similarly for --enable-pcretest-readline
  
  if test "$enable_pcretest_libreadline" = "yes"; then
@@ -53,13 +53,11 @@
 -    echo "** Cannot --enable-pcretest-readline because readline/history.h was not found."
 -    exit 1
 -  fi
--  LIBREADLINE="-lreadline"
-+  LIBREADLINE="-ledit"
- fi
- 
- 
-@@ -18564,7 +18532,7 @@
-     Build static libs ............... : ${enable_static}
+   if test -z "$LIBREADLINE"; then
+     echo "** Cannot --enable-pcretest-readline because readline library was not found."
+     exit 1
+@@ -19893,7 +19861,7 @@
+     Buffer size for pcregrep ........ : ${with_pcregrep_bufsize}
      Link pcregrep with libz ......... : ${enable_pcregrep_libz}
      Link pcregrep with libbz2 ....... : ${enable_pcregrep_libbz2}
 -    Link pcretest with libreadline .. : ${enable_pcretest_libreadline}
