Update Zope port to 2.7.0 (woot!)
git-svn-id: https://svn.macports.org/repository/macports/trunk/dports@5456 d073be05-634f-4543-b044-5fe20cf6d1d6

diff --git a/www/zope/files/zopectl b/www/zope/files/zopectl
--- a/www/zope/files/zopectl
+++ b/www/zope/files/zopectl
@@ -1,35 +1,20 @@
 #!/bin/sh
-# Zope zopectl script, from:
-# http://www.zope.org/Members/jonms/MacOSXService
 
-ZOPEHOME=%%ZOPEBASE%%
-PATH=.:$PATH
+ZOPEINST=%%ZOPEINST%%
+ZOPEUSER=%%ZOPEUSER%%
+CURRUSER=`([ -x /usr/bin/id ] && /usr/bin/id -un) || echo unknown`
 
-case "$1" in
-	start)
-		echo -n "Starting Zope"
-		$ZOPEHOME/start -u %%ZOPEUSER%% -p %%CGIBINDIR%%/Zope.cgi \
-            >> $ZOPEHOME/var/error.log 2>&1 &
-		echo ".  Please wait a few moments for Zope to fully start."
+case "$CURRUSER" in
+	$ZOPEUSER)
+		exec $ZOPEINST/bin/zopectl "$@"
 		;;
-	stop)
-		echo -n "Stopping Zope"
-		$ZOPEHOME/stop && rm -f $ZOPEHOME/var/pcgi.pid \
-		$ZOPEHOME/var/pcgi.soc
-		echo ".  Please wait a few moments for Zope to fully stop."
-		;;
-	restart)
-		$0 stop
-		sleep 3
-		$0 start
-		;;
-	reload)
-		$0 restart
+	root)
+		exec su -m $ZOPEUSER -c "$ZOPEINST/bin/zopectl $*"
 		;;
 	*)
-		echo "Usage: zopectl [start|stop|restart|reload]"
+		echo "Error: Must be run as user 'root' or '$ZOPEUSER' not '$CURRUSER'!"
+		echo " "
+		$ZOPEINST/bin/zopectl -h | sed "s/^Usage:/& sudo [-u $ZOPEUSER]/"
 		exit 1
 		;;
 esac
-
-exit 0
