qt4-mac : compiler testing and comment changes only, so no rev-bump.
* move C++11 test, if variant is set, to pre-qmake build;

* add tests for CPATH, fconstant_cfstrings, and ObjC(++) blocks;

* patch configure to handle all of these tests, and error out if any fail;

* blacklist many compilers for not supplying required functionality;

* add macports-clang-3.0 back into non-C++11 support since it seems to honor CPATH;

* redo comments in Portfile to reflect the above changes, and tweak a couple comments for correctness.

git-svn-id: https://svn.macports.org/repository/macports/trunk/dports@102339 d073be05-634f-4543-b044-5fe20cf6d1d6

diff --git a/aqua/qt4-mac/files/patch-configure.diff b/aqua/qt4-mac/files/patch-configure.diff
--- a/aqua/qt4-mac/files/patch-configure.diff
+++ b/aqua/qt4-mac/files/patch-configure.diff
@@ -1,5 +1,5 @@
---- configure.orig	2013-01-20 15:22:24.000000000 -0500
-+++ configure	2013-01-22 15:50:39.000000000 -0500
+--- configure.orig	2013-01-30 20:33:36.000000000 -0500
++++ configure	2013-01-30 20:53:16.000000000 -0500
 @@ -918,12 +918,14 @@
  CFG_ICU=auto
  CFG_SYSTEM_PROXIES=no
@@ -48,7 +48,62 @@
      system-proxies)
          if [ "$VAL" = "yes" ] || [ "$VAL" = "no" ]; then
              CFG_SYSTEM_PROXIES="$VAL"
-@@ -3685,6 +3697,19 @@
+@@ -3451,6 +3463,38 @@
+     CFG_MAC_XARCH=no
+ fi
+ 
++# detect required support for CPATH
++if "$mactests/cpath/cpath.test" "$TEST_COMPILER" "$OPT_VERBOSE" "$mactests/cpath" ; then
++    echo >&2 "error: The compiler ($TEST_COMPILER) does not seem to support the CPATH environment variable, which is required to compile qt4-mac using MacPorts when compiling on Mac OS X."
++    exit 1
++fi
++
++# detect required support for -fconstant-cfstrings
++if "$mactests/fconstant_cfstrings.test" "$TEST_COMPILER" "$OPT_VERBOSE" "$mactests" ; then
++    echo >&2 "error: The compiler ($TEST_COMPILER) does not seem to support the -fconstant-cfstrings flag, which is used extensively by the Qt build system when compiling on Mac OS X."
++    exit 1
++fi
++
++# detect required support for Objective-C blocks (^) on the mac
++if "$mactests/objc_block/objc_block.test" "$TEST_COMPILER" "$OPT_VERBOSE" "$mactests/objc_block" ; then
++    echo >&2 "error: The compiler ($TEST_COMPILER) does not seem to support the Objective-C blocks (^), which are used by Qt when compiling on Mac OS X."
++    exit 1
++fi
++
++# Detect C++11 support, only if requested
++if [ "$CFG_CXX11" = "yes" ]; then
++    if "$mactests/c++11/c++11.test" "$TEST_COMPILER" "$OPT_VERBOSE" "$mactests/c++11" ; then
++	echo >&2 "error: C++11 support was requested, but the compiler ($TEST_COMPILER) does not seem to support C++11."
++        exit 1
++    fi
++fi
++
++# detect required support for -Xarch
++if "$mactests/xarch.test" "$TEST_COMPILER" "$OPT_VERBOSE" "$mactests" ; then
++    echo >&2 "error: The compiler ($TEST_COMPILER) does not seem to support the -Xarch flag, which is used extensively by the Qt build system when compiling on Mac OS X."
++    exit 1
++fi
++
+ #auto-detect DWARF2 on the mac
+ if [ "$PLATFORM_MAC" = "yes" ] && [ "$CFG_MAC_DWARF2" = "auto" ]; then
+     if "$mactests/dwarf2.test" "$TEST_COMPILER" "$OPT_VERBOSE" "$mactests" ; then
+@@ -3460,15 +3504,6 @@
+     fi
+ fi
+ 
+-# auto-detect support for -Xarch on the mac
+-if [ "$PLATFORM_MAC" = "yes" ] && [ "$CFG_MAC_XARCH" = "auto" ]; then
+-    if "$mactests/xarch.test" "$TEST_COMPILER" "$OPT_VERBOSE" "$mactests" ; then
+-        CFG_MAC_XARCH=no
+-    else
+-        CFG_MAC_XARCH=yes
+-    fi
+-fi
+-
+ # don't autodetect support for separate debug info on objcopy when
+ # cross-compiling as lots of toolchains seems to have problems with this
+ if [ "$QT_CROSS_COMPILE" = "yes" ] && [ "$CFG_SEPARATE_DEBUG_INFO" = "auto" ]; then
+@@ -3685,6 +3720,19 @@
      fi
      QT_INSTALL_LIBS=`"$relpath/config.tests/unix/makeabs" "$QT_INSTALL_LIBS"`
  
@@ -68,7 +123,7 @@
      #bins
      if [ -z "$QT_INSTALL_BINS" ]; then #default
          if [ "$CFG_PREFIX_INSTALL" = "no" ]; then
-@@ -4752,6 +4777,7 @@
+@@ -4752,6 +4800,7 @@
  DOCUMENTATION_PATH_STR=`"$relpath/config.tests/unix/padstring" 268 "qt_docspath=$QT_INSTALL_DOCS"`
  HEADERS_PATH_STR=`"$relpath/config.tests/unix/padstring" 268 "qt_hdrspath=$QT_INSTALL_HEADERS"`
  LIBRARIES_PATH_STR=`"$relpath/config.tests/unix/padstring" 268 "qt_libspath=$QT_INSTALL_LIBS"`
@@ -76,7 +131,7 @@
  BINARIES_PATH_STR=`"$relpath/config.tests/unix/padstring" 268 "qt_binspath=$QT_INSTALL_BINS"`
  PLUGINS_PATH_STR=`"$relpath/config.tests/unix/padstring" 268 "qt_plugpath=$QT_INSTALL_PLUGINS"`
  IMPORTS_PATH_STR=`"$relpath/config.tests/unix/padstring" 268 "qt_impspath=$QT_INSTALL_IMPORTS"`
-@@ -4777,6 +4803,7 @@
+@@ -4777,6 +4826,7 @@
      HOSTDOCUMENTATION_PATH_STR=`"$relpath/config.tests/unix/padstring" 268 "qt_docspath=$QT_HOST_PREFIX/doc"`
      HOSTHEADERS_PATH_STR=`"$relpath/config.tests/unix/padstring" 268 "qt_hdrspath=$QT_HOST_PREFIX/include"`
      HOSTLIBRARIES_PATH_STR=`"$relpath/config.tests/unix/padstring" 268 "qt_libspath=$QT_HOST_PREFIX/lib"`
@@ -84,7 +139,7 @@
      HOSTBINARIES_PATH_STR=`"$relpath/config.tests/unix/padstring" 268 "qt_binspath=$QT_HOST_PREFIX/bin"`
      HOSTPLUGINS_PATH_STR=`"$relpath/config.tests/unix/padstring" 268 "qt_plugpath=$QT_HOST_PREFIX/plugins"`
      HOSTIMPORTS_PATH_STR=`"$relpath/config.tests/unix/padstring" 268 "qt_impspath=$QT_HOST_PREFIX/IMPORTS"`
-@@ -4794,6 +4821,7 @@
+@@ -4794,6 +4844,7 @@
  static const char qt_configure_documentation_path_str[256 + 12] = "$HOSTDOCUMENTATION_PATH_STR";
  static const char qt_configure_headers_path_str      [256 + 12] = "$HOSTHEADERS_PATH_STR";
  static const char qt_configure_libraries_path_str    [256 + 12] = "$HOSTLIBRARIES_PATH_STR";
@@ -92,7 +147,7 @@
  static const char qt_configure_binaries_path_str     [256 + 12] = "$HOSTBINARIES_PATH_STR";
  static const char qt_configure_plugins_path_str      [256 + 12] = "$HOSTPLUGINS_PATH_STR";
  static const char qt_configure_imports_path_str      [256 + 12] = "$HOSTIMPORTS_PATH_STR";
-@@ -4812,6 +4840,7 @@
+@@ -4812,6 +4863,7 @@
  static const char qt_configure_documentation_path_str[256 + 12] = "$DOCUMENTATION_PATH_STR";
  static const char qt_configure_headers_path_str      [256 + 12] = "$HEADERS_PATH_STR";
  static const char qt_configure_libraries_path_str    [256 + 12] = "$LIBRARIES_PATH_STR";
@@ -100,7 +155,7 @@
  static const char qt_configure_binaries_path_str     [256 + 12] = "$BINARIES_PATH_STR";
  static const char qt_configure_plugins_path_str      [256 + 12] = "$PLUGINS_PATH_STR";
  static const char qt_configure_imports_path_str      [256 + 12] = "$IMPORTS_PATH_STR";
-@@ -4837,6 +4866,7 @@
+@@ -4837,6 +4889,7 @@
  #define QT_CONFIGURE_DOCUMENTATION_PATH qt_configure_documentation_path_str + 12;
  #define QT_CONFIGURE_HEADERS_PATH qt_configure_headers_path_str + 12;
  #define QT_CONFIGURE_LIBRARIES_PATH qt_configure_libraries_path_str + 12;
@@ -108,7 +163,7 @@
  #define QT_CONFIGURE_BINARIES_PATH qt_configure_binaries_path_str + 12;
  #define QT_CONFIGURE_PLUGINS_PATH qt_configure_plugins_path_str + 12;
  #define QT_CONFIGURE_IMPORTS_PATH qt_configure_imports_path_str + 12;
-@@ -4996,20 +5026,11 @@
+@@ -4996,20 +5049,11 @@
              EXTRA_CXXFLAGS="$EXTRA_CXXFLAGS \$(CARBON_CFLAGS)"
              EXTRA_OBJS="qsettings_mac.o qcore_mac.o"
              EXTRA_SRCS="\"$relpath/src/corelib/io/qsettings_mac.cpp\" \"$relpath/src/corelib/kernel/qcore_mac.cpp\""
@@ -134,24 +189,7 @@
  	    if [ '!' -z "$CFG_SDK" ]; then
  		echo "SDK_LFLAGS =-Wl,-syslibroot,$CFG_SDK" >>"$mkfile"
  		echo "SDK_CFLAGS =-isysroot $CFG_SDK" >>"$mkfile"
-@@ -5118,6 +5139,16 @@
- # tests that need qmake
- #-------------------------------------------------------------------------------
- 
-+# Detect C++11 support, only if requested
-+if [ "$CFG_CXX11" = "yes" ]; then
-+    if "$unixtests/compile.test" "$XQMAKESPEC" "$QMAKE_CONFIG" $OPT_VERBOSE "$relpath" "$outpath" config.tests/unix/c++11 "c++11" $L_FLAGS $I_FLAGS $l_FLAGS; then
-+	CFG_CXX11=yes
-+    else
-+        echo "C++11 support was requested but the functionality test for C++11 failed!"
-+        exit 101
-+    fi
-+fi
-+
- # detect availability of float math.h functions
- if "$unixtests/compile.test" "$XQMAKESPEC" "$QMAKE_CONFIG" $OPT_VERBOSE "$relpath" "$outpath" config.tests/unix/floatmath "floatmath" $L_FLAGS $I_FLAGS $l_FLAGS; then
-     CFG_USE_FLOATMATH=yes
-@@ -7161,16 +7192,8 @@
+@@ -7161,16 +7205,8 @@
  
  # set the global Mac deployment target. This is overridden on an arch-by-arch basis
  # in some cases, see code further down
@@ -170,7 +208,7 @@
  
  # disable Qt 3 support on VxWorks, Symbian and INTEGRITY
  case "$XPLATFORM" in
-@@ -7447,6 +7470,10 @@
+@@ -7447,6 +7483,10 @@
      QCONFIG_FLAGS="$QCONFIG_FLAGS QT_NO_GUI"
  fi
  
@@ -181,7 +219,7 @@
  
  if [ "x$PLATFORM_MAC" = "xyes" ] && [ "$XPLATFORM_MINGW" != "yes" ] && [ "$XPLATFORM_SYMBIAN" != "yes" ]; then
      #On Mac we implicitly link against libz, so we
-@@ -7910,28 +7937,32 @@
+@@ -7910,28 +7950,32 @@
  # env. variable. 
  if [ "$PLATFORM_MAC" = "yes" ] && [ "$CFG_MAC_XARCH" != "no" ] ; then
      if echo "$CFG_MAC_ARCHS" | grep '\<x86\>' > /dev/null 2>&1; then
@@ -230,7 +268,7 @@
      fi
  fi
  
-@@ -8689,6 +8720,7 @@
+@@ -8689,6 +8733,7 @@
  QMAKE_RCC        = \$\$QT_BUILD_TREE/bin/rcc
  QMAKE_QDBUSXML2CPP = \$\$QT_BUILD_TREE/bin/qdbusxml2cpp
  QMAKE_INCDIR_QT  = \$\$QT_BUILD_TREE/include
@@ -238,7 +276,7 @@
  QMAKE_LIBDIR_QT  = \$\$QT_BUILD_TREE/lib
  
  EOF
-@@ -8727,6 +8759,11 @@
+@@ -8727,6 +8772,11 @@
      echo "DEFINES *= QT_EDITION=QT_EDITION_DESKTOP" >> "$CACHEFILE.tmp"
  fi
  
@@ -250,7 +288,7 @@
  #dump in the OPENSSL_LIBS info
  if [ '!' -z "$OPENSSL_LIBS" ]; then
      echo "OPENSSL_LIBS = $OPENSSL_LIBS" >> "$CACHEFILE.tmp"
-@@ -8886,6 +8923,7 @@
+@@ -8886,6 +8936,7 @@
  else
     echo "Debug .................. $CFG_DEBUG"
  fi
