qt4-mac: fix build on aarch64
Closes: https://trac.macports.org/ticket/68496

diff --git a/aqua/qt4-mac/files/patch-configure.diff b/aqua/qt4-mac/files/patch-configure.diff
--- a/aqua/qt4-mac/files/patch-configure.diff
+++ b/aqua/qt4-mac/files/patch-configure.diff
@@ -34,6 +34,15 @@
      qtnamespace)
          QT_NAMESPACE="$VAL"
          ;;
+@@ -1692,7 +1698,7 @@
+             case `uname -p` in
+             i386) NATIVE_64_ARCH="x86_64" ;;
+             powerpc) NATIVE_64_ARCH="ppc64" ;;
+-            *)   echo "WARNING: Can't detect CPU architecture for macx-g++-64" ;;
++            arm) NATIVE_64_ARCH="arm64" ;;
+             esac
+ 	    if [ ! -z "$NATIVE_64_ARCH" ]; then
+ 		QTCONFIG_CONFIG="$QTCONFIG_CONFIG $NATIVE_64_ARCH"
 @@ -2519,6 +2524,13 @@
              UNKNOWN_OPT=yes
          fi
@@ -48,6 +57,23 @@
      system-proxies)
          if [ "$VAL" = "yes" ] || [ "$VAL" = "no" ]; then
              CFG_SYSTEM_PROXIES="$VAL"
+@@ -3370,14 +3382,14 @@
+ # process CFG_MAC_ARCHS
+ if [ "$PLATFORM_MAC" = "yes" ]; then
+ #   check -arch arguments for validity.
+-    ALLOWED="x86 ppc x86_64 ppc64 i386 arm armv6 armv7"
++    ALLOWED="x86 ppc x86_64 ppc64 i386 arm armv6 armv7 arm64"
+     # Save the list so we can re-write it using only valid values
+     CFG_MAC_ARCHS_IN="$CFG_MAC_ARCHS"
+     CFG_MAC_ARCHS=
+     for i in $CFG_MAC_ARCHS_IN
+     do 
+         if echo "$ALLOWED" | grep -w -v "$i" > /dev/null 2>&1; then
+-            echo "Unknown architecture: \"$i\". Supported architectures: x86[i386] ppc x86_64 ppc64 arm armv6 armv7";
++            echo "Unknown architecture: \"$i\". Supported architectures: x86[i386] ppc x86_64 ppc64 arm armv6 armv7 arm64";
+             exit 2;
+         fi
+         if [ "$i" = "i386" -o "$i" = "x86" ]; then
 @@ -3460,6 +3472,53 @@
      CFG_MAC_XARCH=no
  fi
@@ -274,7 +300,7 @@
  
  if [ "x$PLATFORM_MAC" = "xyes" ] && [ "$XPLATFORM_MINGW" != "yes" ] && [ "$XPLATFORM_SYMBIAN" != "yes" ]; then
      #On Mac we implicitly link against libz, so we
-@@ -7986,28 +8037,32 @@
+@@ -7986,29 +8037,40 @@
          ;;
      *)
          if echo "$CFG_MAC_ARCHS" | grep '\<x86\>' > /dev/null 2>&1; then
@@ -321,9 +347,17 @@
 +            QMakeVar add QMAKE_OBJECTIVE_CFLAGS_PPC_64 "-arch ppc64 -Xarch_ppc64 -mmacosx-version-min=@MACOSX_DEPLOYMENT_TARGET@"
 +            QMakeVar add QMAKE_OBJECTIVE_CXXFLAGS_PPC_64 "-arch ppc64 -Xarch_ppc64 -mmacosx-version-min=@MACOSX_DEPLOYMENT_TARGET@"
          fi
++        if echo "$CFG_MAC_ARCHS" | grep '\<arm64\>' > /dev/null 2>&1; then
++            QMakeVar add QMAKE_CFLAGS "-Xarch_arm64 -mmacosx-version-min=@MACOSX_DEPLOYMENT_TARGET@"
++            QMakeVar add QMAKE_CXXFLAGS "-Xarch_arm64 -mmacosx-version-min=@MACOSX_DEPLOYMENT_TARGET@"
++            QMakeVar add QMAKE_LFLAGS "-Xarch_arm64 -mmacosx-version-min=@MACOSX_DEPLOYMENT_TARGET@"
++            QMakeVar add QMAKE_OBJECTIVE_CFLAGS_ARM_64 "-arch arm64 -Xarch_arm64 -mmacosx-version-min=@MACOSX_DEPLOYMENT_TARGET@"
++            QMakeVar add QMAKE_OBJECTIVE_CXXFLAGS_ARM_64 "-arch arm64 -Xarch_arm64 -mmacosx-version-min=@MACOSX_DEPLOYMENT_TARGET@"
++        fi
          ;;
      esac
-@@ -8772,6 +8827,7 @@
+ fi
+@@ -8772,6 +8830,7 @@
  QMAKE_RCC        = \$\$QT_BUILD_TREE/bin/rcc
  QMAKE_QDBUSXML2CPP = \$\$QT_BUILD_TREE/bin/qdbusxml2cpp
  QMAKE_INCDIR_QT  = \$\$QT_BUILD_TREE/include
@@ -331,7 +365,7 @@
  QMAKE_LIBDIR_QT  = \$\$QT_BUILD_TREE/lib
  
  EOF
-@@ -8810,6 +8866,11 @@
+@@ -8810,6 +8869,11 @@
      echo "DEFINES *= QT_EDITION=QT_EDITION_DESKTOP" >> "$CACHEFILE.tmp"
  fi
  
