qt4-mac : perform testing for ObjC blocks on 10.6 and newer only; addresses ticket https://trac.macports.org/ticket/37994.
git-svn-id: https://svn.macports.org/repository/macports/trunk/dports@102936 d073be05-634f-4543-b044-5fe20cf6d1d6

diff --git a/aqua/qt4-mac/files/patch-configure.diff b/aqua/qt4-mac/files/patch-configure.diff
--- a/aqua/qt4-mac/files/patch-configure.diff
+++ b/aqua/qt4-mac/files/patch-configure.diff
@@ -1,5 +1,5 @@
---- configure.orig	2012-11-23 05:11:23.000000000 -0500
-+++ configure	2013-01-31 12:49:12.000000000 -0500
+--- configure.orig	2013-02-10 21:03:10.000000000 -0500
++++ configure	2013-02-10 21:22:49.000000000 -0500
 @@ -918,12 +918,14 @@
  CFG_ICU=auto
  CFG_SYSTEM_PROXIES=no
@@ -48,7 +48,7 @@
      system-proxies)
          if [ "$VAL" = "yes" ] || [ "$VAL" = "no" ]; then
              CFG_SYSTEM_PROXIES="$VAL"
-@@ -3451,6 +3463,44 @@
+@@ -3451,6 +3463,53 @@
      CFG_MAC_XARCH=no
  fi
  
@@ -70,11 +70,20 @@
 +    exit 1
 +fi
 +
-+# detect required support for Objective-C blocks (^) on the mac
-+if "$mactests/objc_block/objc_block.test" "$TEST_COMPILER" "$OPT_VERBOSE" "$mactests/objc_block" ; then
-+    echo >&2 "error: The compiler ($TEST_COMPILER) does not seem to support the Objective-C blocks (^), which are used by Qt when compiling on Mac OS X."
-+    exit 1
-+fi
++# detect required support for Objective-C blocks (^) on the mac,
++# but only on 10.6 ("uname -r" == 10.X) and newer
++case "$UNAME_SYSTEM:$UNAME_RELEASE" in
++    Darwin:[0-9].*)
++	;;
++    Darwin*)
++	if "$mactests/objc_block/objc_block.test" "$TEST_COMPILER" "$OPT_VERBOSE" "$mactests/objc_block" ; then
++	    echo >&2 "error: The compiler ($TEST_COMPILER) does not seem to support the Objective-C blocks (^), which are used by Qt when compiling on Mac OS X 10.6 and newer."
++	    exit 1
++	fi
++	;;
++    *)
++	;;
++esac
 +
 +# Detect C++11 support, only if requested
 +if [ "$CFG_CXX11" = "yes" ]; then
@@ -93,7 +102,7 @@
  #auto-detect DWARF2 on the mac
  if [ "$PLATFORM_MAC" = "yes" ] && [ "$CFG_MAC_DWARF2" = "auto" ]; then
      if "$mactests/dwarf2.test" "$TEST_COMPILER" "$OPT_VERBOSE" "$mactests" ; then
-@@ -3460,15 +3510,6 @@
+@@ -3460,15 +3519,6 @@
      fi
  fi
  
@@ -109,7 +118,7 @@
  # don't autodetect support for separate debug info on objcopy when
  # cross-compiling as lots of toolchains seems to have problems with this
  if [ "$QT_CROSS_COMPILE" = "yes" ] && [ "$CFG_SEPARATE_DEBUG_INFO" = "auto" ]; then
-@@ -3685,6 +3726,19 @@
+@@ -3685,6 +3735,19 @@
      fi
      QT_INSTALL_LIBS=`"$relpath/config.tests/unix/makeabs" "$QT_INSTALL_LIBS"`
  
@@ -129,7 +138,7 @@
      #bins
      if [ -z "$QT_INSTALL_BINS" ]; then #default
          if [ "$CFG_PREFIX_INSTALL" = "no" ]; then
-@@ -4752,6 +4806,7 @@
+@@ -4752,6 +4815,7 @@
  DOCUMENTATION_PATH_STR=`"$relpath/config.tests/unix/padstring" 268 "qt_docspath=$QT_INSTALL_DOCS"`
  HEADERS_PATH_STR=`"$relpath/config.tests/unix/padstring" 268 "qt_hdrspath=$QT_INSTALL_HEADERS"`
  LIBRARIES_PATH_STR=`"$relpath/config.tests/unix/padstring" 268 "qt_libspath=$QT_INSTALL_LIBS"`
@@ -137,7 +146,7 @@
  BINARIES_PATH_STR=`"$relpath/config.tests/unix/padstring" 268 "qt_binspath=$QT_INSTALL_BINS"`
  PLUGINS_PATH_STR=`"$relpath/config.tests/unix/padstring" 268 "qt_plugpath=$QT_INSTALL_PLUGINS"`
  IMPORTS_PATH_STR=`"$relpath/config.tests/unix/padstring" 268 "qt_impspath=$QT_INSTALL_IMPORTS"`
-@@ -4777,6 +4832,7 @@
+@@ -4777,6 +4841,7 @@
      HOSTDOCUMENTATION_PATH_STR=`"$relpath/config.tests/unix/padstring" 268 "qt_docspath=$QT_HOST_PREFIX/doc"`
      HOSTHEADERS_PATH_STR=`"$relpath/config.tests/unix/padstring" 268 "qt_hdrspath=$QT_HOST_PREFIX/include"`
      HOSTLIBRARIES_PATH_STR=`"$relpath/config.tests/unix/padstring" 268 "qt_libspath=$QT_HOST_PREFIX/lib"`
@@ -145,7 +154,7 @@
      HOSTBINARIES_PATH_STR=`"$relpath/config.tests/unix/padstring" 268 "qt_binspath=$QT_HOST_PREFIX/bin"`
      HOSTPLUGINS_PATH_STR=`"$relpath/config.tests/unix/padstring" 268 "qt_plugpath=$QT_HOST_PREFIX/plugins"`
      HOSTIMPORTS_PATH_STR=`"$relpath/config.tests/unix/padstring" 268 "qt_impspath=$QT_HOST_PREFIX/IMPORTS"`
-@@ -4794,6 +4850,7 @@
+@@ -4794,6 +4859,7 @@
  static const char qt_configure_documentation_path_str[256 + 12] = "$HOSTDOCUMENTATION_PATH_STR";
  static const char qt_configure_headers_path_str      [256 + 12] = "$HOSTHEADERS_PATH_STR";
  static const char qt_configure_libraries_path_str    [256 + 12] = "$HOSTLIBRARIES_PATH_STR";
@@ -153,7 +162,7 @@
  static const char qt_configure_binaries_path_str     [256 + 12] = "$HOSTBINARIES_PATH_STR";
  static const char qt_configure_plugins_path_str      [256 + 12] = "$HOSTPLUGINS_PATH_STR";
  static const char qt_configure_imports_path_str      [256 + 12] = "$HOSTIMPORTS_PATH_STR";
-@@ -4812,6 +4869,7 @@
+@@ -4812,6 +4878,7 @@
  static const char qt_configure_documentation_path_str[256 + 12] = "$DOCUMENTATION_PATH_STR";
  static const char qt_configure_headers_path_str      [256 + 12] = "$HEADERS_PATH_STR";
  static const char qt_configure_libraries_path_str    [256 + 12] = "$LIBRARIES_PATH_STR";
@@ -161,7 +170,7 @@
  static const char qt_configure_binaries_path_str     [256 + 12] = "$BINARIES_PATH_STR";
  static const char qt_configure_plugins_path_str      [256 + 12] = "$PLUGINS_PATH_STR";
  static const char qt_configure_imports_path_str      [256 + 12] = "$IMPORTS_PATH_STR";
-@@ -4837,6 +4895,7 @@
+@@ -4837,6 +4904,7 @@
  #define QT_CONFIGURE_DOCUMENTATION_PATH qt_configure_documentation_path_str + 12;
  #define QT_CONFIGURE_HEADERS_PATH qt_configure_headers_path_str + 12;
  #define QT_CONFIGURE_LIBRARIES_PATH qt_configure_libraries_path_str + 12;
@@ -169,7 +178,7 @@
  #define QT_CONFIGURE_BINARIES_PATH qt_configure_binaries_path_str + 12;
  #define QT_CONFIGURE_PLUGINS_PATH qt_configure_plugins_path_str + 12;
  #define QT_CONFIGURE_IMPORTS_PATH qt_configure_imports_path_str + 12;
-@@ -4996,20 +5055,11 @@
+@@ -4996,20 +5064,11 @@
              EXTRA_CXXFLAGS="$EXTRA_CXXFLAGS \$(CARBON_CFLAGS)"
              EXTRA_OBJS="qsettings_mac.o qcore_mac.o"
              EXTRA_SRCS="\"$relpath/src/corelib/io/qsettings_mac.cpp\" \"$relpath/src/corelib/kernel/qcore_mac.cpp\""
@@ -195,7 +204,7 @@
  	    if [ '!' -z "$CFG_SDK" ]; then
  		echo "SDK_LFLAGS =-Wl,-syslibroot,$CFG_SDK" >>"$mkfile"
  		echo "SDK_CFLAGS =-isysroot $CFG_SDK" >>"$mkfile"
-@@ -7161,16 +7211,8 @@
+@@ -7161,16 +7220,8 @@
  
  # set the global Mac deployment target. This is overridden on an arch-by-arch basis
  # in some cases, see code further down
@@ -214,7 +223,7 @@
  
  # disable Qt 3 support on VxWorks, Symbian and INTEGRITY
  case "$XPLATFORM" in
-@@ -7447,6 +7489,10 @@
+@@ -7447,6 +7498,10 @@
      QCONFIG_FLAGS="$QCONFIG_FLAGS QT_NO_GUI"
  fi
  
@@ -225,7 +234,7 @@
  
  if [ "x$PLATFORM_MAC" = "xyes" ] && [ "$XPLATFORM_MINGW" != "yes" ] && [ "$XPLATFORM_SYMBIAN" != "yes" ]; then
      #On Mac we implicitly link against libz, so we
-@@ -7910,28 +7956,32 @@
+@@ -7910,28 +7965,32 @@
  # env. variable. 
  if [ "$PLATFORM_MAC" = "yes" ] && [ "$CFG_MAC_XARCH" != "no" ] ; then
      if echo "$CFG_MAC_ARCHS" | grep '\<x86\>' > /dev/null 2>&1; then
@@ -274,7 +283,7 @@
      fi
  fi
  
-@@ -8689,6 +8739,7 @@
+@@ -8689,6 +8748,7 @@
  QMAKE_RCC        = \$\$QT_BUILD_TREE/bin/rcc
  QMAKE_QDBUSXML2CPP = \$\$QT_BUILD_TREE/bin/qdbusxml2cpp
  QMAKE_INCDIR_QT  = \$\$QT_BUILD_TREE/include
@@ -282,7 +291,7 @@
  QMAKE_LIBDIR_QT  = \$\$QT_BUILD_TREE/lib
  
  EOF
-@@ -8727,6 +8778,11 @@
+@@ -8727,6 +8787,11 @@
      echo "DEFINES *= QT_EDITION=QT_EDITION_DESKTOP" >> "$CACHEFILE.tmp"
  fi
  
@@ -294,7 +303,7 @@
  #dump in the OPENSSL_LIBS info
  if [ '!' -z "$OPENSSL_LIBS" ]; then
      echo "OPENSSL_LIBS = $OPENSSL_LIBS" >> "$CACHEFILE.tmp"
-@@ -8886,6 +8942,7 @@
+@@ -8886,6 +8951,7 @@
  else
     echo "Debug .................. $CFG_DEBUG"
  fi
