make this incentive a little nicer
git-svn-id: https://svn.macports.org/repository/macports/trunk/dports@9225 d073be05-634f-4543-b044-5fe20cf6d1d6

diff --git a/aqua/Growl/files/iport b/aqua/Growl/files/iport
--- a/aqua/Growl/files/iport
+++ b/aqua/Growl/files/iport
@@ -1,5 +1,11 @@
 #!/bin/sh
 PREFIX=__PREFIX__
+GROWL=${PREFIX}/bin/growlnotify
 
-${PREFIX}/bin/port $* | tail -n 4 | ${PREFIX}/bin/growlnotify DarwinPorts 2>&1
+${PREFIX}/bin/port $*
 
+if [ $? -eq 0 ]; then
+	echo -e "success:\n\t${*}" | ${GROWL} DarwinPorts
+else
+	echo -e "error:\n\t${*}" | ${GROWL} DarwinPorts
+fi
