correction bugs

diff --git a/science/gwyddion/files/patch-gtk-osx-application-gtk2.diff b/science/gwyddion/files/patch-gtk-osx-application-gtk2.diff
--- a/science/gwyddion/files/patch-gtk-osx-application-gtk2.diff
+++ b/science/gwyddion/files/patch-gtk-osx-application-gtk2.diff
@@ -1,38 +1,38 @@
---- configure.old	2015-06-25 21:54:31.000000000 +0200
-+++ configure	2015-06-25 21:54:48.000000000 +0200
-@@ -19616,12 +19616,12 @@
+--- configure.old	2023-02-06 16:00:18.000000000 +0100
++++ configure	2023-02-06 15:59:12.000000000 +0100
+@@ -22399,12 +22399,12 @@
          pkg_cv_GTK_MAC_CFLAGS="$GTK_MAC_CFLAGS"
      else
          if test -n "$PKG_CONFIG" && \
--    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gtk-mac-integration\""; } >&5
+-    { { printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gtk-mac-integration\""; } >&5
 -  ($PKG_CONFIG --exists --print-errors "gtk-mac-integration") 2>&5
-+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gtk-mac-integration-gtk2\""; } >&5
++    { { printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gtk-mac-integration-gtk2\""; } >&5
 +  ($PKG_CONFIG --exists --print-errors "gtk-mac-integration-gtk2") 2>&5
    ac_status=$?
-   $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+   printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
    test $ac_status = 0; }; then
 -  pkg_cv_GTK_MAC_CFLAGS=`$PKG_CONFIG --cflags "gtk-mac-integration" 2>/dev/null`
 +  pkg_cv_GTK_MAC_CFLAGS=`$PKG_CONFIG --cflags "gtk-mac-integration-gtk2" 2>/dev/null`
  else
    pkg_failed=yes
  fi
-@@ -19634,12 +19634,12 @@
+@@ -22417,12 +22417,12 @@
          pkg_cv_GTK_MAC_LIBS="$GTK_MAC_LIBS"
      else
          if test -n "$PKG_CONFIG" && \
--    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gtk-mac-integration\""; } >&5
+-    { { printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gtk-mac-integration\""; } >&5
 -  ($PKG_CONFIG --exists --print-errors "gtk-mac-integration") 2>&5
-+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gtk-mac-integration-gtk2\""; } >&5
++    { { printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"gtk-mac-integration-gtk2\""; } >&5
 +  ($PKG_CONFIG --exists --print-errors "gtk-mac-integration-gtk2") 2>&5
    ac_status=$?
-   $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+   printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
    test $ac_status = 0; }; then
 -  pkg_cv_GTK_MAC_LIBS=`$PKG_CONFIG --libs "gtk-mac-integration" 2>/dev/null`
 +  pkg_cv_GTK_MAC_LIBS=`$PKG_CONFIG --libs "gtk-mac-integration-gtk2" 2>/dev/null`
  else
    pkg_failed=yes
  fi
-@@ -19658,9 +19658,9 @@
+@@ -22441,9 +22441,9 @@
          _pkg_short_errors_supported=no
  fi
          if test $_pkg_short_errors_supported = yes; then
