update to v2.9.5.1, remove .turd files, fix some permissions
git-svn-id: https://svn.macports.org/repository/macports/trunk/dports@9305 d073be05-634f-4543-b044-5fe20cf6d1d6

diff --git a/sysutils/fcron/files/patch-configure b/sysutils/fcron/files/patch-configure
--- a/sysutils/fcron/files/patch-configure
+++ b/sysutils/fcron/files/patch-configure
@@ -1,6 +1,24 @@
---- configure	Thu Apr 29 22:48:40 2004
-+++ configure.new	Fri Sep  3 12:28:17 2004
-@@ -11274,20 +11274,12 @@
+--- configure	Sun Nov 14 17:27:35 2004
++++ configure.new	Tue Nov 16 14:17:17 2004
+@@ -11352,17 +11352,9 @@
+     fi
+     ;;
+   *)
+-    if test -d "$withval"; then
+       etcdir="$withval"
+       echo "$as_me:$LINENO: result: $withval" >&5
+ echo "${ECHO_T}$withval" >&6
+-    else
+-      { { echo "$as_me:$LINENO: error:
+-Directory $withval does not exist" >&5
+-echo "$as_me: error:
+-Directory $withval does not exist" >&2;}
+-   { (exit 1); exit 1; }; }
+-    fi
+     ;;
+   esac
+ else
+@@ -11423,20 +11415,12 @@
      fi
      ;;
    *)
@@ -21,7 +39,7 @@
      ;;
    esac
  else
-@@ -11353,20 +11345,12 @@
+@@ -11502,20 +11486,12 @@
      fi
      ;;
    *)
