ncview: adjust configure patch to better support users who already have netcdf4 installed with openmpi (https://trac.macports.org/ticket/33828)
git-svn-id: https://svn.macports.org/repository/macports/trunk/dports@99347 d073be05-634f-4543-b044-5fe20cf6d1d6

diff --git a/science/ncview/files/patch-configure.diff b/science/ncview/files/patch-configure.diff
--- a/science/ncview/files/patch-configure.diff
+++ b/science/ncview/files/patch-configure.diff
@@ -1,5 +1,21 @@
---- configure.orig	2012-03-29 21:27:50.000000000 +0200
-+++ configure	2012-03-29 21:46:40.000000000 +0200
+--- configure.orig	2011-07-18 12:14:52.000000000 -0500
++++ configure	2012-11-02 23:38:02.000000000 -0500
+@@ -2035,13 +2035,13 @@
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }
+-{ (ac_try="$ac_compiler -V >&5"
++{ (ac_try="$ac_compiler -v >&5"
+ case "(($ac_try" in
+   *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+   *) ac_try_echo=$ac_try;;
+ esac
+ eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+-  (eval "$ac_compiler -V >&5") 2>&5
++  (eval "$ac_compiler -v >&5") 2>&5
+   ac_status=$?
+   echo "$as_me:$LINENO: \$? = $ac_status" >&5
+   (exit $ac_status); }
 @@ -8252,7 +8252,7 @@
  	echo "** Could not find the png.h file, so -frames support will not be included  **"
  	echo "** Install the PNG library (and development headers) to fix this           **"
@@ -18,3 +34,36 @@
  PNG_PRESENT=no
  if test $PNG_INC_PRESENT = yes; then
  	if test x$PNG_LIBDIR != x; then
+@@ -8645,32 +8645,6 @@
+ if test x$NETCDF_CC_TEST_SAME = xcc; then
+ 	NETCDF_CC_TEST_SAME=gcc
+ fi
+-if test x$CC_TEST_SAME != x$NETCDF_CC_TEST_SAME; then
+-	echo "======================================================================"
+-	echo "Configuration error: You specified that the \"$CC\" C compiler should be"
+-	echo "used to build ncview, but the netcdf library was compiled with the \"$NETCDF_CC\""
+-	echo "compiler.  Here is the path where I found the netcdf library:"
+-	echo "     $NETCDF_LDFLAGS"
+-	echo "You must use the same compiler for ncview as was used to build the netcdf library!"
+-	echo " "
+-	echo "There are two possible ways to fix this."
+-	echo " "
+-	echo "1) Download the netcdf library and compile it with the $CC compiler,"
+-	echo "install it, and try again to build ncview.  NOTE that if you do this,"
+-	echo "you might have more than one version of the netcdf library on your system,"
+-	echo "built with differnt compilers, which can get confusing.  If you do this,"
+-	echo "you will have to specify the path to the (new) version of nc-config"
+-	echo "that was compiled using the $CC compiler by configuring ncview in a "
+-	echo "way similar to this:"
+-	echo " "
+-	echo "   ./configure --with-nc-config=/path/to/newly/compiled/nc-config"
+-	echo " "
+-	echo "2) Configure ncview to use the $NETCDF_CC compiler."
+-	echo "To do this, set environmental variable CC to $NETCDF_CC"
+-	echo "and run ./configure again"
+-	echo "==================================================================="
+-	exit -1
+-fi
+ 
+ #----------------------------------------------------------------------------------
+ # Construct our RPATH flags.  Idea here is that we have LDFLAGS that might look,
