mirror job: try to recover from extract failure

diff --git a/.github/workflows/mirror.yml b/.github/workflows/mirror.yml
--- a/.github/workflows/mirror.yml
+++ b/.github/workflows/mirror.yml
@@ -142,8 +142,11 @@ jobs:
                             BZIP2=/opt/local/bin/lbzip2
                         fi
                       fi
-                      tar -C tarball -xf "portindex-${LAST_COMMIT}.tar.bz2" \
-                        --use-compress-program "$BZIP2"
+                      if ! tar -C tarball -xf "portindex-${LAST_COMMIT}.tar.bz2" \
+                        --use-compress-program "$BZIP2" ; then
+                            echo "Extracting failed, starting from scratch."
+                            rm -rf tarball
+                      fi
                       rm -f "portindex-${LAST_COMMIT}.tar.bz2"
                   else
                       echo "Fetch failed, starting from scratch."
